### ISSUE TITLE
Thoughts after the Study Group + Mozilla Science Lab meeting (Mar 2)

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#2]
**Note:** I'll be editing this as I come back to it... But this is more to get a
discussion going. Also, sorry if some of the stuff doesn't make sense. It still
is coming out of my brain...

Some initial thoughts I had...

- Might be good to have a Marketing Exec position..?
- We need (maybe) better branding. This relates to marketing, but I think it
would be good to have a brand, so that when students think of the group they
have a certain image... however, there may be an issue with that... see next
point.

## Specifics for targeting skill level:

Targeting an audience. I agree we need more advanced users and also more
beginners.. However, as per above, these are two distinct and opposing views in
terms of marketing/branding... When students think of the group, how do we keep
the image of being friendly to *both* skill levels.. ?

- What do beginners want? I assume (based on my experience and my own past when I was one):
    - To be more productive (probably pretty important)
    - Be more efficient
    - Be in control and less stressed (hopefully)
    - Do better science/not worry about doing it wrong (more or less)
    - Better job prospects and career/cv enhancement (this is probably pretty
    important)
    - These all probably benefit more from practice/code-along-based lessons

- What do advanced users want? Again, I am assuming here but:
    - Learn deeper issues and concepts (could get from teaching or
    code/technique sharing, probably benefits more from lecture style lessons[1])
    - Get advice/tips/tricks from other advanced users
    - Maybe want to teach other students what they know
    - Get potential collaborators?
    - Become even more productive/efficient (I think this is a never ending ambition :P )
    
I think we could benefit from some market research here... What does our
audience really need/want (if they are aware of the need that is... :P ).

[1]: One thing I've noticed is that for more advanced sessions, I usually listen
rather than actually code anything. But for things that I am a complete nooob at
(like python when I first started coming to these sessions), it was helpful to
actually type along (again, this is my experience and what I've seen so far).

## General marketing/advertising issues/thoughts

Right now, I feel there are too many places for beginners to go to get info on
this study group. Issues, in both events + studyGroup repos, website, lesson
folder on studyGroup repo, wiki page for schedule. It might be a good idea to
focus down. As per the targeting/marketing thoughts above, maybe have one single
location (+watching Events) to suggest for beginners or advanced users. Ideas:

- Beginners always encouraged to go to website and optionally follow the Events
repo.
    - We should get some consistency with this and really push others to always
    recommend this location first.
    - Have the schedule on the website too.
    
- Advanced users suggested to follow Events repo + studyGroup repo? Or maybe
another repo for advanced users? Should we really be mixing issues related to
fixing the website/studyGroup repo vs topics that are related to general
programming, social projects, etc? Like, what if I want to add an issue (more
for myself + also for the record) about fixing a website issue... Do I want all
the other users who follow the repo to see that? Thoughts?

### Overall branding:

I've been thinking maybe it might be a good idea to combine all the separate
attempts at teaching coding to researchers/students here at UofT. Have that
unified 'organization' have it's mission statement be:

> Learn to code and get better at it! 

(or something like that...). Then we can have several distinct and targeted
'branches' to market and brand their own way (but still under the umbrella). So
far there are (that I am aware) these groups/sessions that teach code:

- My own code as manuscript GPS workshop (5 session workshop series for R so far that I co-instruct with Sarah)
- One other (unspecified programming language) data viz (1 session), also in GPS
- SWC workshops (eg. Gerstein, SickKids, etc)
- The Study Group
- (A possible, but still not concrete) GPS coworking sessions with coding helpers

If we had a unified approach to things, we could direct all prospect learners to
a single location, which they can branch from there. We could also have a
consistent framework, mission/goal, and marketing structure, which would cut
down on the difficulty students face *just trying to find these resources*. It
is also convenient for faculty, staff, and instructors on getting the word out
there and for using it as a resource too to direct students.

So like we could have the informal structure of the study group and market it as
such, then the GPS workshops, again marketing as such. But all in the end point
back to the overarching theme/goal.

(Misc thoughts: Need to get librarians on board. Get GPS and deans (eg. faculty
of medicine) on board.)
Get SGS on board.

## Thoughts on structuring the sessions/repo contents

- To differentiate between beginners and advanced users maybe have an
alternating and separate schedules? Cycle between beginner and advanced...

- Transfer wiki contents to website, like the contributing, schedule, etc. I
like the wiki idea for other projects, but for I feel for these purposes, there
are too many other things. Simplicity is key here I think (could learn a thing
from Apple)

## Persona thingy 

Note: I didn't read what the exercise really was, I'm just typing my thoughts here

- Beginner:
    - Time strapped
    - Learning a lot of things at once
    - Maybe a bit overwhelmed
    - Probably hesitant to put something else on their learning plate
    - Wary of learning 'programming', which probably has a 'mythical' status in
    their minds (it does mine!) so they probably almost immediately don't think
    they can do it (kinda like math and statistics... most people shy away from
    learning those cause they associate them with difficult/hard to learn/they
    (assume) they can't learn it). Might be good to 'unbrand' or maybe 'rebrand'
    what programming/coding is.
    
- Advanced:
    - Maybe less time strapped/more effective at time management (given they are
    advanced and know a thing or two about being efficient thro programming
    concepts)
    - May not think of themselves as 'advanced' or even be aware that they are
    advanced (that was me for a loooong time)
    - May not think they have the skills to teach (I've heard this many times)
    
```
end_thoughts()
```

**Comment by mbonsma** [comment]
```
begin_thoughts()
```
First, I agree with almost all of your observations. Here are my comments on what you've said here.

* Marketing exec: I've been thinking of this as my job, but we could certainly consider adding it.

## Specifics for targeting skill level:
I completely agree with your assessment of what beginner and advanced users want, and I think it's possible for our group to provide what both want, especially in the cases where they clearly overlap: advanced users teaching, beginner users following along.

## Website / repo / email where-to-go issues
Lots of communication channels means greater potential of reaching more people, but also makes for a confusing situation, as you rightly pointed out. 

**Repositories:** our original intent was to have the main StudyGroup repo be a place for people who want to be more involved in the group, so that includes things like website maintenance. However, the 'interest' posts that I've been making might be of interest to people just following the events repo too. But the reason for the separate Events repo was to avoid notification spam.

Possible solutions:
* To avoid over-messaging people who primarily just want event updates, we could include a small digest at the bottom of each event post and email message with links to the 'interest' issues in the StudyGroup repo. 

**Website/schedule:** we could consider making the distinction between repositories more clear on the website. I agree that the website should be the first point of contact always. 
The schedule in the wiki was originally meant for planning purposes and not as the go-to event reference. BUT this is problematic if we're not posting events on the website until 1 or 2 weeks beforehand. 
I'm fine with the lesson content arrangement as it is now - the website links to GitHub, so no matter which way you come from you end up in the right place. 
Touching on a later point: I agree, contributing guide should be on website. 

Possible solutions:
* Get event posts up for the whole term ASAP - even if it means leaving the instructor field blank or editing them later. Then we can stop directing people to the wiki for the full schedule.
* Include more in-depth info on the website - like, a short paragraph describing our specific group.

## Overall branding:

This sounds like a huge and scary endeavor to me, but I think if it's possible it would be fantastic. You're right, it involves getting a lot of people on board. Practically, I think this could be accomplished with a single website, provided:
* Everyone who had anything to do with programming directed people to go there (we'll be fighting institutional inertia here).
* It had nice links and information on everything out there. 

## Persona exercise:

We'll talk about this one on Thursday, but here are my additions and proposed changes to your list:


- Beginner:
    - Time strapped
    - Learning a lot of things at once
    - ~~Maybe a bit~~ Definitely overwhelmed
    - Probably hesitant to put something else on their learning plate
    - Wary of learning 'programming', which probably has a 'mythical' status in
    their minds (it does mine!) so they probably almost immediately don't think
    they can do it (kinda like math and statistics... most people shy away from
    learning those cause they associate them with difficult/hard to learn/they
    (assume) they can't learn it). **Might be good to 'unbrand' or maybe 'rebrand'
    what programming/coding is.** +1 And present it in a way that they can see its usefulness to them.
    - Doesn't know very many people outside their group.
    - Might want to make friends, or conversely might be afraid of strangers, especially 'experts'.
    
- Advanced:
    - Maybe less time strapped/more effective at time management (given they are
    advanced and know a thing or two about being efficient thro programming
    concepts)
    - May not think of themselves as 'advanced' or even be aware that they are
    advanced (that was me for a loooong time)
    - May not think they have the skills to teach (I've heard this many times)
    - Super opposed to wasting time on anything - they'll stop coming if they think they're wasting time.

And also we can add everything in your list of the interests of beginner and advanced users. 

```
end_thoughts()
```

**Comment by mbonsma** [comment]
**Quick notes on being welcoming (borrowed from [CERN Study Group](https://github.com/CERNStudyGroup))**

* We should keep encouraging people to add themselves to the 'Who We Are' section.
* Maybe an issue like [this one](https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/26) for people to introduce themselves? They also have one for [introducing your project](https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/24).

**Comment by linamnt** [comment]
On this note (both of which sound like a great idea!), I remember we were talking about having a place where people can see how people are currently using code in their research projects, as well as a note saying "You can contact me/ask me questions about...{insert topics}", so this would be the perfect place to do so!

**Comment by mbonsma** [comment]
Yeah! And an issue is really easy to implement, although issues do get confusing. Maybe we can be more better at our labels.

**Comment by lwjohnst86** [comment]
Something I thought of while walking after the meeting this morning was, why not have a conditional question for the topics based on perceived skill level?

So for example, there is an initial question of "What would you consider yourself to be in terms of coding? Beginner, Intermediate, or Advanced?"... Then based on the response, different session topics could be shown. So for beginner, they would only get to choose more 'beginner-friendly' topics like introduction to R/python/etc/code review/best practices/etc, while intermediate and advanced would get more options to choose from (looping, debugging, making packages, etc/if they want to teach). That way we don't intimidate beginners with options that make (probably) no sense to them, but still include people that are familiar with those things.

That way we could also include it all as a single survey... tho I personally still prefer there being two surveys. But up to everyone else.

Just my 2 cents :smile:
