### ISSUE TITLE
Eventbrite Tax Form

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/council#259]
We got an email from Eventbrite asking us to fill out tax info:

> We need your taxpayer information for U.S. tax purposes. If we do not receive this information by the time you exceed 200 orders, we must withhold on future payouts.

This issue is basically a reminder to deal with this, and ask BMO how we would fill out the form, since we aren't exactly a business or a not-for-profit.

**Comment by lwjohnst86** [comment]
From what I remember, according to Canadian law, unless we make more than $10,000 in revenue, we don't need to be classified as a not-for-profit, corporation, or whatever.

However, since Eventbrite is US-based, this makes it a bit challenging. I guess the simplest solution is to not go over 200 orders / year. That translates to what, 200/40 or 50 so about 4 workshops per year. Have you guys gone over that limit?

I would email Eventbrite asking.

**Comment by linamnt** [comment]
@lwjohnst86 Thanks Luke, I'll email Eventbrite, hopefully it's pretty straightforward and it's as easy as staying under the 200 orders/year.

**Comment by linamnt** [comment]
For reference: https://www.eventbrite.ca/support/articles/en_US/Troubleshooting/do-i-need-to-submit-taxpayer-information-u-s-citizens?lg=en_CA

**Comment by lwjohnst86** [comment]
Seems they only need information, but it doesn't do anything. You can even use your own name "Name: Enter your legal name (individual)" as per the reference. So it doesn't seem like a big deal thankfully.

**Comment by QuLogic** [comment]
Seems more like we'd use the W-8BEN-E? https://www.eventbrite.ca/support/articles/en_CA/Troubleshooting/do-i-need-to-submit-taxpayer-information-non-u-s-citizens?lg=en_CA

**Comment by linamnt** [comment]
So there is actually no way to email Eventbrite directly without buying premium membership, so we have to follow the help guides available :scream:

**Comment by linamnt** [comment]
This is fine if we keep under 200 orders a year. Close for now until we get to that point.
