### ISSUE TITLE
Freely available online Jupyter Notebook environments

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#288]
Hey guys!

I was recently looking for a way to run jupyter notebooks without having to setup jupyter-hub on my own (it seemed to be more involved than I hoped). I went through [the ones mentioned here](https://blog.ouseful.info/2019/01/04/more-than-ten-free-hosted-jupyter-notebook-environments-you-can-try-right-now/) and I thought I would share the most useful here since we were talking about setting up a notebook binder at some point:

-   https://notebooks.ai/ Optional to create account (but necessary for saving progress). Most up to date version of `seaborn`.
-   https://codeocean.com/ Account required. Sign up with institutional email for extra storage and run time. Requires slight setup of specifying which packages to install.
-   https://colab.research.google.com/notebooks/welcome.ipynb Account required. Google branded design.
-   https://jupyter.org/try No account required. Not possible to save progress. Lots of font-related warnings when plotting (I had to silence all Python warnings in the end).

My testing was essentially importing `pandas` and `seaborn` and running

``` python
iris = sns.load_dataset('iris')
sns.pairplot(iris, hue='species')
```

so not very exhaustive but just enough to have people follow along with introductory data analysis in Python even if they don't have a local install or something is not working for them. I could PR this to the setup process or somewhere else if you want to have it. Or just keep it in this issue forever... Let me know!

**Comment by linamnt** [comment]
This is awesome! Thanks @joelostblom, this could work for future cases when working with younger students who may not have their own laptops and when we're using some computer lab.

**Comment by linamnt** [comment]
If you want, it would be great to PR to the set-up instructions :)

**Comment by joelostblom** [comment]
Great point with the kids! I'm very excited you are working with younger students now, super cool! See https://github.com/UofTCoders/studyGroup/pull/439 for the PR

**Comment by QuLogic** [comment]
Way back at the beginning of the year, I thought binder would have been pretty useful for that first lesson when we hadn't sent out instructions and many didn't have things installed. We could have pointed those attendees at the online version while anaconda installed.

The biggest problem was that binder automatically determined the dependencies to install from the top level directory, and since we have an R `DESCRIPTION` setup there, it takes a while to download stuff we don't need for, e.g., a Python lesson. If it did that on a subdirectory basis, that'd work great for us.
