### ISSUE TITLE
Improvements to teaching onboarding

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/council#34]
Some ways we can improve experience for new instructors:
* link to study group handbook for instructors (https://mozillascience.github.io/studyGroupHandbook/)
* enforce submitting lesson material beforehand
* more guidelines on what we mean by a particular topic
* more re-use of lessons from other study groups: https://github.com/mozillascience/studyGroupLessons/issues

**Comment by lwjohnst86** [comment]
Definitely agree with @mbonsma. I have a few suggestions that I think could be created into a README or something for instructors to read/use for making and giving lessons (which I'll assign to myself :stuck_out_tongue_winking_eye: ).

- The [handbook](https://mozillascience.github.io/studyGroupHandbook/lessons.html#reuse) is useful but it mainly emphasizes making the actual written lesson file. So maybe expand on it and develop our own `CONTRIBUTING.md` or `instructor/README.md` file to include:
  - Generalizability of the code (so that it is as field-independent as possible. E.g. no need to discuss your own research)
  - Emphasizing code rather than the data (or make sure the data is also as field-independent as possible), esp. the applicability, usage, meaning, etc.
  - Try to assume as little as possible about the audience
  - Try to do a 'code along', as in write the code as you go, with as little shown to the audience as possible (print off code/notes if need be)
  - Keep code as simple as possible while still getting at the concept (it is only an hour).
- Include maybe a FAQ for instructors that we add to over time.
- How to deal with off-topic, though well-intentioned, audience questions.
- Some mechanism in place to provide feedback to instructors if they so wish.
- Some mechanism in place to deal with instructors who go off topic or who are not prepared (obviously being polite about it).


Also a note on the webcasting from the hankbook: **Never distribute a recording of another person without their written consent.** We should get written consent via the issue or something before hand. Maybe we can create an issue that lists all instructors and their written consent as a comment or something? And keep it active/open?

**Comment by QuLogic** [comment]
> Emphasizing code rather than the data

Or even better, not require _any_ data. This is difficult in some cases, of course, but if you can rely on some package's (which was asked to be installed earlier) sample data, that'd be a lot easier. It's always troubling to get people to download stuff over WiFi in that room.

Of course, getting the lesson early helps with this because we can point people there before hand.

> Keep code as simple as possible

A somewhat misquoted Einstein quote comes to mind there...

**Comment by lwjohnst86** [comment]
@QuLogic completely agree about the data bit and using like sample/built-in datasets. I guess I was meaning what the data is specifically shouldn't matter (eg. that it is climate data or bacterial data or genomic data, etc.), what matters is the code that uses the data.

**Comment by linamnt** [comment]
These all look like really good suggestions, I will make sure in the future to provide better support via explaining to them in the email and linking to resources from the study group and the file we made for new instructors when I'm in contact with them!

**Comment by mbonsma** [comment]
Here's what the SFU study group has done: https://github.com/sciprog-sfu/sciprog-sfu.github.io/blob/master/lessons/README.md

Zannah's training materials: https://docs.google.com/document/d/1abNCjcvsdJmUQNSuwln7gkrKEGK3CZTyie5x2NNp0zw/edit

**Comment by lwjohnst86** [comment]
See <https://github.com/UofTCoders/studyGroup/issues/162>
